set(_CATKIN_CURRENT_PACKAGE "reel_euro2021")
set(reel_euro2021_VERSION "0.0.0")
set(reel_euro2021_MAINTAINER "Farid <faridadwani@insat.u-carthage.tn>")
set(reel_euro2021_PACKAGE_FORMAT "2")
set(reel_euro2021_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "goal" "ta7wil" "mission" "message_generation" "geometry_msgs" "genmsgs" "std_msgs_msgs")
set(reel_euro2021_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msg")
set(reel_euro2021_BUILDTOOL_DEPENDS "catkin")
set(reel_euro2021_BUILDTOOL_EXPORT_DEPENDS )
set(reel_euro2021_EXEC_DEPENDS "geometry_msgs" "genmsgs" "std_msgs_msgs" "roscpp" "rospy" "std_msgs" "message_runtime")
set(reel_euro2021_RUN_DEPENDS "geometry_msgs" "genmsgs" "std_msgs_msgs" "roscpp" "rospy" "std_msgs" "message_runtime" "std_msg")
set(reel_euro2021_TEST_DEPENDS )
set(reel_euro2021_DOC_DEPENDS )
set(reel_euro2021_URL_WEBSITE "")
set(reel_euro2021_URL_BUGTRACKER "")
set(reel_euro2021_URL_REPOSITORY "")
set(reel_euro2021_DEPRECATED "")