!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  footprint: '[]'
  footprint_padding: 0.01
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      footprint: '[]'
      footprint_padding: 0.01
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      height: 2
      id: 0
      name: Default
      origin_x: 0.0
      origin_y: 0.0
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      publish_frequency: 7.0
      resolution: 0.1
      robot_radius: 0.15
      state: true
      transform_tolerance: 0.5
      type: ''
      update_frequency: 5.0
      width: 3
    state: []
  height: 2
  origin_x: 0.0
  origin_y: 0.0
  publish_frequency: 7.0
  resolution: 0.1
  robot_radius: 0.15
  transform_tolerance: 0.5
  update_frequency: 5.0
  width: 3
state: []
