robot_radius: 0.15

transform_tolerance: 0.5
map_type: costmap
width: 2
height: 3
obstacle_layer:
 z_voxels : 16
 unknown_threshold: 16
 mark_threshold : 0
 enabled: true
 obstacle_range: 3.5
 raytrace_range: 8
 resolution: 0.01
#  inflation_radius: 0.2
 track_unknown_space: false
 combination_method: 1

 observation_sources: laser_scan_sensor
 laser_scan_sensor: {data_type: LaserScan, topic: scan, marking: true, clearing: true}


# inflation_layer:
#   enabled:              true
#   cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
#   inflation_radius:     0.2   # max distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  map_topic:            "map"
