set(_CATKIN_CURRENT_PACKAGE "web_package")
set(web_package_VERSION "0.0.0")
set(web_package_MAINTAINER "farid <farid@todo.todo>")
set(web_package_PACKAGE_FORMAT "2")
set(web_package_BUILD_DEPENDS "message_generation" "rosconsole" "roscpp" "roscpp_serialization" "rostime" "std_msgs")
set(web_package_BUILD_EXPORT_DEPENDS )
set(web_package_BUILDTOOL_DEPENDS "catkin")
set(web_package_BUILDTOOL_EXPORT_DEPENDS )
set(web_package_EXEC_DEPENDS "message_runtime" "rosconsole" "roscpp" "roscpp_serialization" "rostime" "std_msgs")
set(web_package_RUN_DEPENDS "message_runtime" "rosconsole" "roscpp" "roscpp_serialization" "rostime" "std_msgs")
set(web_package_TEST_DEPENDS )
set(web_package_DOC_DEPENDS )
set(web_package_URL_WEBSITE "")
set(web_package_URL_BUGTRACKER "")
set(web_package_URL_REPOSITORY "")
set(web_package_DEPRECATED "")