robot_radius: 0.15

obstacle_range: 3
global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10
  publish_frequency: 10
  static_map: false
  resolution: 0.01
  
 
  # transform_tolerance: 1.0
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
    
  inflation_layer:
    cost_scaling_factor: 10
    inflate_unknown: false
    inflation_radius: 1.75
    
    static_layer:
     enabled: true

